server:
  AppVersion: 1.0.0
  Port: :5000
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: eyJhbGciOiJIUzI1NiJ9.
  CookieName: eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY2OTMyMDc0NiwiaWF0IjoxNjY5MzIwNzQ2fQ.6fxDv-cb9uJhWv2EmhyCAr3fvgbz3UaIXgJ4d5YpsvU
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false
  MaxConnectionIdle: 5
  Timeout: 15
  MaxConnectionAge: 5
  Time: 120

Smtp:
  Host: smtp.gmail.com
  Port: 465
  User: cupastate@gmail.com
  Password: 5nC7JXYNv3iH4q8

rabbitmq:
  Host: localhost
  Port: 5672
  User: guest
  Password: guest
  Exchange: emails-exchange
  Queue: emails-queue
  RoutingKey: emails-routing-key
  ConsumerTag: emails-consumer
  WorkerPoolSize: 24


logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: mails_db
  PostgresqlSslmode: false
  PgDriver: pgx

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

cookie:
  Name: eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY2OTMyMDc0NiwiaWF0IjoxNjY5MzIwNzQ2fQ.6fxDv-cb9uJhWv2EmhyCAr3fvgbz3UaIXgJ4d5YpsvU
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-session
  Expire: 3600

metrics:
  Url: 0.0.0.0:7070
  ServiceName: auth_microservice

aws:
  Endpoint: 127.0.0.1:9000
  MinioAccessKey: minio
  MinioSecretKey: minio123
  UseSSL: false
  MinioEndpoint: http://127.0.0.1:9000

jaeger:
  Host: localhost:6831
  ServiceName: mail_service
  LogSpans: false
